name: Reward-HiroTeam
author: HiroTeam-Willy
version: 1.0.0
api: 3.0.0
main: HiroTeam\Reward\main
website: https://github.com/HiroshimaTeam

commands:
  reward:
    description: Récompense journalière !
    usage: /reward
    
